docs: updating node sync instructions
terra-money/docs pull request #473
Opened 2022-09-20 20:44 UTC by terran6

Updating instructions on how to sync a node on Pisco testnet and Phoenix-1 mainnet.

2022-09-20 21:15 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +```
You could put `cd core` here. It might make it easier to read.

2022-09-20 21:23 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +From here, you can [monitor the sync](#monitor-the-sync) and make sure to check on your node periodically to ensure optimal performance.
This sentence is a run-on. You can put a comma before "and," or you can make it 2 sentences:

" From here, you can [monitor the sync](#monitor-the-sync).  Make sure to check on your node periodically to ensure optimal performance."

2022-09-20 21:24 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +### Pisco testnet
I would number all of the substeps in this section using an ordered list. It helps readers remember what step they left off on. Same for the Pheonix section.

2022-09-20 21:26 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +After running these commands, make sure that you have switched to the correct version of Terrad by running the command:
Change to "...Terrad by running the following command:"

2022-09-20 21:27 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +```
Add `cd core` to this codebox.

2022-09-20 21:29 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +From here, you can [monitor the sync](#monitor-the-sync) and make sure to check on your node periodically to ensure optimal performance.
This sentence is a run-on. You can put a comma before "and," or you can make it 2 sentences:

" From here, you can [monitor the sync](https://github.com/terra-money/docs/pull/473/files#monitor-the-sync). Make sure to check on your node periodically to ensure optimal performance."

2022-09-20 21:30 UTC, evanorti commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +```
cd core

2022-09-20 21:45 UTC, evanorti approved these changes

2022-09-20 22:39 UTC, octalmage requested changes
just a few comments

2022-09-20 22:39 UTC, octalmage commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +The process for syncing your full node from genesis will differ between the Pisco testnet and Phoenix-1 mainnet networks. You may proceed with the instructions corresponding with your [chosen network
```suggestion
The process for syncing your full node from genesis will differ between the Pisco testnet and Phoenix mainnet networks. You may proceed with the instructions corresponding with your [chosen network](./join-a-network.mdx#join-a-public-network) below.
```

I would make these match to keep it consistent.

2022-09-20 22:39 UTC, octalmage commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +If you would like to sync your node using the Pisco testnet, you will need to utilize version `v2.0.0-rc.0` of Terrad up until the block height of 890,000.  To switch to this version of Terrad, chang
```suggestion
If you would like to sync your node using the Pisco testnet, you will need to utilize version `v2.0.0-rc.0` of Terrad up until the block height of 890,000.  To switch to this version of `terrad`, change into your `core` directory and execute the following commands in your terminal:
```

I see that you've been stylizing Terrad with a capital T, but since this is the name of a binary I think it should be lowercase, and maybe even in backticks so it's easy to copy.

2022-09-20 22:39 UTC, octalmage commented on docs/full-node/run-a-full-terra-node/sync.mdx
> +Syncing will halt at block 890,000, at which point you will need to change the version of Terrad and then resume the syncing process.
`890000` is only for pisco,  `838500` is the correct height for mainnet.

2022-09-23 17:22 UTC, octalmage approved these changes
LGTM 

![](http://media2.giphy.com/media/l2R0dZTDEZ9rS2O6k/giphy.gif)

2022-09-23 17:24 UTC, merged