Fixed polkachu address book download link
terra-money/docs pull request #480
Opened 2022-09-29 11:33 UTC by Akbar30Bill

Updated the addressbook download link

2022-10-06 11:17 UTC, Aminkavoos commented
****

2022-10-06 11:17 UTC, Aminkavoos commented
> ****

2022-10-06 11:17 UTC, Aminkavoos approved these changes

2022-10-08 23:46 UTC, terran6 requested changes
Hey @Akbar30Bill.  Thanks for the update, but it seems that your branch is unable to merge.  Please either make the appropriate change or create a new branch with the same changes.  Thanks!

2022-10-19 22:01 UTC, closed without merging