Update Validator Pages to reflect Columbus-5
terra-money/docs pull request #74
Opened 2021-08-21 01:46 UTC by evanorti

Update validator changes to reflect Columbus 5 changes.
All validator pages reviewed and edited for grammar, spelling, wordflow, structure. Columbus 5 changes implemented to validator pages and updated.

pages updated:
dev/README.md
dev/spec-auth.md
dev/spec-bank.md
dev/spec-distribution.md
dev/spec-governance.md
dev/spec-slashing.md
dev/spec-supply.md
dev/spec-treasury.md
Luna.md
terrad/treasury.md
validator/README.md
validator/faq.md
validator/security.md
validator/setup.md
validator/troubleshooting.md

2021-08-24 19:56 UTC, ouiliame requested changes

2021-08-24 19:56 UTC, ouiliame commented on docs/dev/README.md
> +   - seigniorage settlement (all seigniorage is burned as of Cloumbus-5)
Typo

2021-08-24 19:56 UTC, ouiliame commented on docs/terrad/treasury.md
> +As of Columbus-5, all
make one line

2021-08-25 00:31 UTC, evanorti commented on docs/dev/README.md
> +   - seigniorage settlement (all seigniorage is burned as of Cloumbus-5)
Changed. Thanks!

2021-08-25 00:32 UTC, evanorti commented
@ouiliame I have implemented the changes.

2021-08-25 01:23 UTC, evanorti commented on docs/terrad/treasury.md
> +As of Columbus-5, all
I have made this one line.

2021-08-26 18:05 UTC, stevenTerra commented on docs/dev/README.md
> +   - seigniorage settlement (all seigniorage is burned as of Columbus-5)
No need for the parentheses here.

2021-08-26 18:11 UTC, stevenTerra commented on docs/dev/README.md
> +   - If at the end of `epoch`, update indicators, burn seigniorage, and recalibrate monetary policy levers (tax-rate, reward-weight) for the next epoch.
The structure here is kind of awkward. It's the "if" at the beginning. Could we just remove it?

2021-08-26 18:34 UTC, stevenTerra commented on docs/dev/README.md
> +Both Terra (of all denominations) and Luna tokens are divisible up to micro-units ($\times 10^{-6}$). The micro-unit is considered the atomic unit of tokens, and cannot be further divided. Below is a
A few things here in this sentence:

- We want to use parenthetical expressions like this one as infrequently as possible. We can usually rewrite the sentence easily without them.
- Microsoft Style Guide, which we're trying to abide by, doesn't hyphenate words that begin with micro unless it will cause confusion.
- The terms above and below can be confusing in translation and, in the past, they've been a problem for accessibility tests. It's generally easier to translate a sentence without them.
- The phrase "at the time of writing" is unnecessary. Everything is considered to be up to date and in the present.

Here's one way to rewrite the sentence:

All denominations of Terra tokens and Luna tokens are divisible up to microunits ($\times 10^{-6}$), which are considered to be the atomic unit of tokens, and they cannot be divided further. The following list shows several denominations that are recognized by the protocol:

2021-08-26 18:46 UTC, stevenTerra commented on docs/dev/spec-slashing.md
> +single slashing period is capped as described [here](https://docs.cosmos.network/v0.43/modules/slashing/01_concepts.html#tombstone-caps).
single slashing period is capped. For more information, see [tombstone caps](https://docs.cosmos.network/v0.43/modules/slashing/01_concepts.html#tombstone-caps).

2021-08-26 18:48 UTC, stevenTerra commented on docs/dev/spec-treasury.md
> +While the Treasury stabilizes miner demand by adjusting rewards, the [`Market`](spec-market.md) module is responsible for Terra price-stability through arbitrage and the market maker.
Let's try to get rid of the passive verb is. Maybe something like: While the Treasury module stabilizes miner demand by adjusting rewards, the [`Market`](spec-market.md) module maintains Terra price-stability through arbitrage and the market maker.

2021-08-26 19:23 UTC, stevenTerra commented on docs/dev/spec-treasury.md
> +These indicators can be used to derive two other values, the **Tax Reward per unit Luna** represented by $\tau = T / \lambda$, used in [Updating Tax Rate](#k-updatetaxpolicy), and **total mining rewa
Let's use the same format for mathematical expressions everywhere and use lowercase where appropriate. So, in this case: These indicators can be used to derive two other values, the **tax reward per unit Luna**, represented by $\tau = T / \lambda$, used in [Updating Tax Rate](#k-updatetaxpolicy), and **total mining rewards**, represented by $R = T + S$, the sum of the tax rewards and the seigniorage rewards, used in [Updating Reward Weight](#k-updaterewardpolicy).

Full disclosure: I haven't looked closely at these items that in uppercase. In general, these things usually aren't proper and should be lowercase.

2021-08-26 19:34 UTC, stevenTerra commented on docs/dev/spec-treasury.md
> +- **Tax Rate:** $r$ adjusts the amount of income coming from Terra transactions, limited by [_tax cap_](#tax-caps).
Consider replacing "coming" with "gained."

2021-08-26 19:42 UTC, stevenTerra commented on docs/dev/spec-treasury.md
> +- **Reward Weight:** $w$ the portion of seigniorage allocated for the reward pool for the ballot winners for correctly voting within the reward band of the weighted median of exchange rate in the [`O
Can we break this one into two sentences?

2021-08-26 19:53 UTC, stevenTerra commented on docs/dev/spec-treasury.md
> +Both the [Tax Rate](#tax-rate) and the [Reward Weight](#reward-weight) are stored as values in the `KVStore`, and can have their values updated through [governance proposals](#governance-proposals) o
- remove the comma after `KVStore`
- change "once passed" to "after they have passed"
- change "will also re-calibrate" to "recalibrates"

2021-08-26 19:55 UTC, stevenTerra commented on docs/luna.md
> +Staking rewards come from two sources: gas (compute fees) and taxes.
"Staking rewards come from gas and taxes."

Add links back to the Gas and Taxes sections

2021-08-27 00:52 UTC, evanorti commented on docs/dev/README.md
> +   - seigniorage settlement (all seigniorage is burned as of Columbus-5)
I will remove these.

2021-08-27 00:56 UTC, evanorti commented on docs/dev/README.md
> +   - If at the end of `epoch`, update indicators, burn seigniorage, and recalibrate monetary policy levers (tax-rate, reward-weight) for the next epoch.
Done.

2021-08-27 01:00 UTC, evanorti commented on docs/dev/README.md
> +Both Terra (of all denominations) and Luna tokens are divisible up to micro-units ($\times 10^{-6}$). The micro-unit is considered the atomic unit of tokens, and cannot be further divided. Below is a
Thanks for the feedback. I have implemented these changes. For brevity, I have been conservative about rewording. Your example is a lot cleaner.

2021-08-27 01:02 UTC, evanorti commented on docs/dev/spec-slashing.md
> +single slashing period is capped as described [here](https://docs.cosmos.network/v0.43/modules/slashing/01_concepts.html#tombstone-caps).
I will reword.

2021-08-27 01:10 UTC, evanorti commented on docs/dev/spec-treasury.md
> +While the Treasury stabilizes miner demand by adjusting rewards, the [`Market`](spec-market.md) module is responsible for Terra price-stability through arbitrage and the market maker.
@stevengregg I have made the changes pertaining to this page in another pull request specifically for treasury.

2021-08-27 01:24 UTC, evanorti commented
@ouiliame I have implemented all changes suggested by you and Steven.

2021-08-27 12:21 UTC, stevenTerra commented on docs/validator/README.md
> +If validators double sign, are frequently offline, or do not participate in governance, their staked Luna (including Luna of users that delegated to them) can be slashed. Penalties can vary depending
If validators double sign, are frequently offline, or do not participate in governance, their staked Luna, including Luna of users that delegated to them, can be slashed. Penalties can vary, depending on the severity of the violation.

2021-08-27 12:24 UTC, stevenTerra commented on docs/validator/README.md
> +We recommend the following for running Terra Core:
We recommend the following system requirements to run Terra core:

2021-08-27 12:27 UTC, stevenTerra commented on docs/validator/security.md
> +Each validator candidate is encouraged to run its operations independently. Diverse individual setups increase the resilience of the network.
Is this more like a recommendation? Could we say, "We recommend that each validator should run its operations independently because diverse, individual setups make the network more resilient."

2021-08-27 12:30 UTC, stevenTerra commented on docs/validator/security.md
> +Sentry nodes can be quickly spun up or used to change IP addresses. Because links to the sentry nodes are in private IP space, an internet based attack can't disturb them directly. This will ensure a
- Add a hyphen: internet-based attack
- Can we replace the naked this that begins the last sentence? I'm not sure what "this" refers to? Is it sentry nodes? Maybe the sentence should be something like, "Sentry nodes ensure ..."

2021-08-27 12:31 UTC, stevenTerra commented on docs/validator/setup.md
> +This is a detailed step-by-step guide for setting up a Terra validator. Please be aware that while it is easy to set up a rudimentary validating node, running a production-quality validator node with
Try to avoid using the naked this. To get rid of it here, consider saying, "The following step-by-step guide describes how to set up a Terra validator."

2021-08-27 12:32 UTC, stevenTerra commented on docs/validator/setup.md
> +Block42 has put together an excellent [step-by-step guide](https://medium.com/block42-blockchain-company/how-to-setup-a-terra-luna-validator-node-860d8ea7aea2)  for setting up a new validator.
change "put together" to "written"

2021-08-27 12:40 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +These are some common problems that you may run into when running a validator node.
Using these here is akin to the naked this problem. Reconstruct the sentence, perhaps like: "You might encounter some of the following common problems when you run a validator node."

2021-08-27 12:41 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +If this occurs, your validator has become auto-unbonded. On the Mainnet, validators unbond if they do not vote on `9500` of the last `10000` blocks (`50` of the last `100` blocks on the testnet). Sin
The naked this problem. Maybe you can reconstruct it in this way: "When your validator has 0 voting power, it is auto-unbonded."

2021-08-27 12:42 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +1. If `terrad` is not running, start it up again:
remove "up"

2021-08-27 12:46 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +The default number of files Linux can open (per-process) is `1024`. `terrad` is known to open more than this amount, causing the process to crash. You can fix this by doing the following:
The default number of files Linux can open per process is `1024`. `terrad` is known to open more than this amount, causing the process to crash. To fix this problem, complete the following steps:

The idea here is that we need a noun after the phrase "the following"

2021-08-27 12:47 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +There are a few reasons why a validator is not active:
A validator might be inactive for one or more of the following reasons:

The idea here is to make the sentence less passive by removing the "there are" phrase

2021-08-27 12:48 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +- The validator is jailed. To solve this, `unjail` the validator:
the naked this problem. Just replace it with "this problem."

2021-08-27 12:54 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +- The validator is not in the active [validator set](https://docs.terra.money/validators.html#delegations). Only the top 130 validators are in this set. The only solution for this is to increase your
the naked this problem

To be in the active validator set, increase your total stake.

2021-08-27 12:55 UTC, stevenTerra commented on docs/validator/troubleshooting.md
> +The Oracle Feeder may be submitting to the wrong network. This is common. The command to run the feeder needs to specify the lite client daemon (LCD):
the naked this

In this case, consider removing "This is common" entirely.

2021-08-27 13:12 UTC, stevenTerra commented on docs/validators.md
> +- **Downtime:** A validator is non-responsive / couldn't be reached for more than an amount of time
no need to hyphenate words that begin with non unless they'll somehow cause confusion.

2021-09-15 23:04 UTC, closed without merging